### ISSUE TITLE
searx.lnode.net: TLS seems not supported on this server

### ISSUE THREAD

**Issue by dalf** [aeris/cryptcheck#48]
https://searx.lnode.net works as expected in Firefox, Chrome and curl.

But cryptcheck returns this result (on command line, same on https://cryptcheck.fr):
```
/cryptcheck/lib/cryptcheck/tls/engine.rb:80:in `fetch_supported_methods': TLS seems not supported on this server (CryptCheck::Tls::Engine::TLSNotAvailableException)
	from /cryptcheck/lib/cryptcheck/tls/engine.rb:54:in `initialize'
	from /cryptcheck/lib/cryptcheck/tls/https/server.rb:10:in `initialize'
	from /cryptcheck/lib/cryptcheck/tls/https/host.rb:8:in `new'
	from /cryptcheck/lib/cryptcheck/tls/https/host.rb:8:in `server'
	from /cryptcheck/lib/cryptcheck/tls/host.rb:39:in `block (2 levels) in initialize'
	from /usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
	from /usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:33:in `catch'
	from /usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /cryptcheck/lib/cryptcheck/tls/host.rb:38:in `block in initialize'
	from /cryptcheck/lib/cryptcheck/tls/host.rb:34:in `collect'
	from /cryptcheck/lib/cryptcheck/tls/host.rb:34:in `initialize'
	from /cryptcheck/lib/cryptcheck/tls/https.rb:7:in `new'
	from /cryptcheck/lib/cryptcheck/tls/https.rb:7:in `analyze'
	from /cryptcheck/bin/cryptcheck:20:in `https'
	from /cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /cryptcheck/bin/cryptcheck:25:in `<main>'
2001:41d0:a:6cb2::1:443 [searx.lnode.net]

Supported methods
TLS seems not supported on this server
/cryptcheck/lib/cryptcheck/tls/engine.rb:80:in `fetch_supported_methods'
/cryptcheck/lib/cryptcheck/tls/engine.rb:54:in `initialize'
/cryptcheck/lib/cryptcheck/tls/https/server.rb:10:in `initialize'
/cryptcheck/lib/cryptcheck/tls/https/host.rb:8:in `new'
/cryptcheck/lib/cryptcheck/tls/https/host.rb:8:in `server'
/cryptcheck/lib/cryptcheck/tls/host.rb:39:in `block (2 levels) in initialize'
/usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/usr/local/rbenv/versions/2.3.8-cryptcheck/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/cryptcheck/lib/cryptcheck/tls/host.rb:38:in `block in initialize'
/cryptcheck/lib/cryptcheck/tls/host.rb:34:in `collect'
/cryptcheck/lib/cryptcheck/tls/host.rb:34:in `initialize'
/cryptcheck/lib/cryptcheck/tls/https.rb:7:in `new'
/cryptcheck/lib/cryptcheck/tls/https.rb:7:in `analyze'
/cryptcheck/bin/cryptcheck:20:in `https'
/cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/cryptcheck/vendor/bundle/ruby/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/cryptcheck/bin/cryptcheck:25:in `<main>'
TLS seems not supported on this server
```

**Comment by dalf** [comment]
Related to https://github.com/aeris/cryptcheck/issues/46
The server supports only TLS 1.3
